<?php
/**
 * Yeti
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 Yeti Theme. (https://github.com/augustash/yeti)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>

<form id="search_mini_form" class="row collapse" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
    <div class="input-box small-9 columns">
        <label class="hide" for="search"><?php echo $this->__('Search:') ?></label>
        <input id="search" type="search" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text required-entry" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" placeholder="<?php echo $this->__('Search entire store here...') ?>" />
    </div>
    <div class="submit-box small-3 columns">
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button postfix search-button"><span><span><?php echo $this->__('Search') ?></span></span></button>
    </div>

    <div id="search_autocomplete" class="search-autocomplete"></div>
    <script type="text/javascript">
    //<![CDATA[
        var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
        searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
    //]]>
    </script>
</form>
