<?php
/**
 * Wicked awesome responsive theme for Magento.
 *
 * @category    Ash
 * @package     Ash_Yeti
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php if($this->getWishlist()->getItemsCount()): ?>
    <button type="submit" name="save_and_share" title="<?php echo $this->__('Share Wishlist') ?>" class="button small secondary no-margin btn-share"><span><span><?php echo $this->__('Share Wishlist') ?></span></span></button>
<?php endif;?>
