<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>

<?php if($this->getWishlist()->getItemsCount() && $this->getWishlist()->isSalable()): ?>
	<li>
    	<button type="button" title="<?php echo $this->__('Add All to Cart') ?>" onclick="addAllWItemsToCart()" class="small button secondary btn-add"><i class="fa fa-shopping-cart"></i> <?php echo $this->__('Add All to Cart') ?></button>
    </li>
<?php endif;?>
