<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>

<?php if($this->getWishlist()->getItemsCount()): ?>
	<li>
    	<button type="submit" name="do" title="<?php echo $this->__('Update Wishlist') ?>" class="small button secondary btn-update"><i class="fa fa-refresh"></i> <?php echo $this->__('Update Wishlist') ?></button>
    </li>
<?php endif;?>
