<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<button type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout right" onclick="review.save();"><span><span><?php echo $this->__('Place Order <i class="fa fa-angle-right"></i>') ?></span></span></button>
