<?php
/**
 * Wicked awesome responsive theme for Magento.
 *
 * @category    Ash
 * @package     Ash_Yeti
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<button type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout right" onclick="review.save();"><?php echo $this->__('Place Order') ?></button>
