<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!doctype html>
<html lang="<?php echo $this->getLang() ?>" class="no-js">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<?php echo $this->getChildHtml('head') ?>
</head>
<!--[if IE 8 ]> <body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().' ie ie8"':'' ?>> <![endif]-->
<!--[if IE 9 ]> <body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().' ie ie9"':'' ?>> <![endif]-->
<!--[if gte IE 9]><!--> <body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>> <!--<![endif]-->
    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('global_notices') ?>
    <?php echo $this->getChildHtml('header') ?>
    <?php echo $this->getChildHtml('breadcrumbs') ?>
    <div class="main-container col1-layout row">
        <section class="large-12 columns">
            <?php echo $this->getChildHtml('global_messages') ?>
            <?php echo $this->getChildHtml('content') ?>
        </section>
    </div>
    <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('global_cookie_notice') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>
    <?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
