<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!doctype html>
<html lang="<?php echo $this->getLang() ?>" class="no-js">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<?php echo $this->getChildHtml('head') ?>
</head>
<!--[if IE 8 ]> <body class="page-popup ie ie8 <?php echo $this->getBodyClass()?$this->getBodyClass() : ''?>"> <![endif]-->
<!--[if IE 9 ]> <body class="page-popup ie ie9 <?php echo $this->getBodyClass()?$this->getBodyClass() : ''?>"> <![endif]-->
<!--[if gte IE 9]><!--> <body class="page-popup <?php echo $this->getBodyClass()?$this->getBodyClass() : ''?>"> <!--<![endif]-->
<div>
    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('content') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
