<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Redirecting...') ?></h1>
</div>
<?php if($this->getMessage()): ?>
    <p><?php echo $this->getMessage() ?></p>
<?php endif; ?>
<?php echo $this->getRedirectOutput() ?>
<?php if(!$this->isHtmlFormRedirect()): ?>
    <p><?php echo $this->__('Click <a href="%s">here</a> if nothing has happened', $this->getTargetURL()) ?></p>
<?php endif; ?>
