<?php
/**
 * Wicked awesome responsive theme for Magento Enterprise.
 *
 * @category    Ash
 * @package     Ash_Yetiee
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php  $_order = $this->getOrder() ?>
<ul class="button-group">
    <?php if($this->helper('rss/order')->isStatusNotificationAllow()): ?>
        <a href="<?php echo $this->helper('rss/order')->getStatusHistoryRssUrl($_order) ?>" class="button tiny secondary link-rss f-none"><?php echo $this->__('Subscribe to Order Status') ?></a>
    <?php endif; ?>
    <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
        <a href="<?php echo $this->getReorderUrl($_order) ?>" class="button tiny secondary link-reorder"><?php echo $this->__('Reorder') ?></a>
    <?php endif ?>
    <a href="<?php echo $this->getPrintUrl($_order) ?>" class="button tiny link-print" onclick="this.target='_blank';"><?php echo $this->__('Print Order') ?></a>
    <?php echo $this->getChildHtml(); ?>
</ul>
