<?php
/**
 * Wicked awesome responsive theme for Magento Enterprise.
 *
 * @category    Ash
 * @package     Ash_Yetiee
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>
<div id="mobile-search" class="top-search mobile-top medium-6 medium-push-6 columns">
    <form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
        <div class="form-search row collapse">
            <div class="small-9 columns">
                <label for="search" class="hide"><?php echo $this->__('Search:') ?></label>
                <input id="search" class="no-margin" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" placeholder="Search entire store..." class="input-text" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" />
            </div>
            <div class="small-3 columns">
                <button type="submit" title="<?php echo $this->__('Search') ?>" class="button postfix no-margin"><?php echo $this->__('Search') ?></button>
            </div>
            <div id="search_autocomplete" class="search-autocomplete"></div>
            <script type="text/javascript">
            //<![CDATA[
                var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
                searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
            //]]>
            </script>
        </div>
    </form>
</div>
