<?php
/**
 * Wicked awesome responsive theme for Magento.
 *
 * @category    Ash
 * @package     Ash_Yeti
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="block block-subscribe">
    <div class="row">
        <div class="large-12 columns">
            <div class="block-title">
                <strong><span><?php echo $this->__('Newsletter') ?></span></strong>
            </div>
            <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
                <div class="block-content row collapse">
                    <div class="input-box small-10 columns">
                        <input type="email" placeholder="Enter email address" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email no-margin" />
                    </div>
                    <div class="actions small-2 columns">
                        <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button postfix no-margin"><i class="fa fa-envelope"></i></button>
                    </div>
                </div>
            </form>
            <script type="text/javascript">
            //<![CDATA[
                var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
            //]]>
            </script>
        </div>
    </div>
</div>
