<?php
/**
 * Wicked awesome responsive theme for Magento.
 *
 * @category    Ash
 * @package     Ash_Yeti
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="main" class="col-main">
<!-- [start] content -->
    <div class="page-title">
        <h2>404 error: Page not found.</h2>
    </div>
<!-- [end] content -->
</div>
