<?php
/**
 * Wicked awesome responsive theme for Magento.
 *
 * @category    Ash
 * @package     Ash_Yeti
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<!-- [start] center -->
    <div id="main" class="col-main">
    <!-- [start] content -->
        <div class="page-title">
            <h2>Service Temporarily Unavailable</h2>
        </div>
        <p>The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.</p>
    <!-- [end] content -->
    </div>
<!-- [end] center -->
