<?php
/**
 * Wicked awesome responsive theme for Magento Enterprise.
 *
 * @category    Ash
 * @package     Ash_Yetiee
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<!doctype html>
<html class="no-js" lang="en">
<head>
<title><?php echo $this->pageTitle?></title>
<base href="<?php echo $this->getSkinUrl()?>" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="robots" content="*" />
<link rel="stylesheet" href="css/foundation.min.css" type="text/css" />
<link rel="stylesheet" href="css/styles.css" type="text/css" />
<link rel="icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
</head>
<body>
    <div class="wrapper row">
        <div class="page medium-8 medium-offset-2 columns">
            <div class="header-container">
                <div class="header">
                    <a href="<?php echo $this->getBaseUrl()?>" title="Magento Commerce" class="logo"><img src="images/logo.png" alt="Magento Commerce" /></a>
                </div>
                <hr>
            </div>
            <div class="main-container">
                <div class="main col1-layout">
                    <?php require_once $contentTemplate; ?>
                </div>
            </div>
            <div class="footer-container">
                <div class="footer">
                    <address class="copyright">Magento is a trademark of Magento Inc. Copyright &copy; 2015 Magento Inc.</address>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
