<?php
/**
 * Wicked awesome responsive theme for Magento.
 *
 * @category    Ash
 * @package     Ash_Yeti
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="col-main">
    <div class="page-title">
        <h2>There has been an error processing your request</h2>
    </div>
    <?php if ($this->showSentMsg): ?>
    <div data-alert class="alert-box success">
        Your message was submitted and will be responded as soon as possible. Thank you for reporting.
    </div>
    <?php endif; ?>
    <?php if ($this->showSendForm): ?>
    <div data-alert class="alert-box warning">
        We are currently experiencing some technical issues. We apologize for the inconvenience and will contact you shortly to resolve the issue. To help us serve you please fill in the form below.
    </div>
        <?php if ($this->showErrorMsg): ?>
    <div data-alert class="alert-box alert">
        Please fill all required fields with valid information
    </div>
        <?php endif; ?>
    <form action="<?php echo "{$this->getBaseUrl(true)}errors/report.php?id={$this->reportId}" ?>" method="post" id="form-validate">
        <fieldset class="fieldset">
            <h2>Personal Information</h2>
            <ul class="form-list group-select no-bullet">
                <li class="fields">
                    <div class="field">
                        <label for="firstname" class="required"><em>*</em>First Name</label>
                        <span class="input-box"><input type="text" name="firstname" id="firstname" value="<?php echo $this->postData['firstName'] ?>" title="First Name" class="required-entry input-text" /></span>
                    </div>
                    <div class="field">
                        <label for="lastname" class="required"><em>*</em>Last Name </label>
                        <span class="input-box"><input type="text" name="lastname" id="lastname" value="<?php echo $this->postData['lastName'] ?>" title="Last Name" class="required-entry input-text" /></span>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="firstname" class="required"><em>*</em>Email Address</label>
                        <span class="input-box"><input type="text" name="email" id="email_address" value="<?php echo $this->postData['email'] ?>" title="Email Address" class="validate-email required-entry input-text" /></span>
                    </div>
                    <div class="field">
                        <label for="firstname">Telephone</label>
                        <span class="input-box"><input type="text" name="telephone" id="telephone" value="<?php echo $this->postData['telephone'] ?>" title="Telephone" class="input-text" /></span>
                    </div>
                </li>
                <li>
                    <div class="input-box">
                        <label for="firstname">Comment</label>
                        <span class="input-box"><textarea name="comment" cols="5" rows="3"><?php echo $this->postData['comment'] ?></textarea></span>
                    </div>
                </li>
            </ul>
        </fieldset>
        <div class="buttons-set form-buttons btn-only">
            <hr>
            <p class="required">* Required Fields</p>
            <button name="submit" class="button right" type="submit">Submit</button>
        </div>
    </form>
    <?php elseif ('' == $this->reportAction): ?>
        <p><em>Exception printing is disabled by default for security reasons.</em></p>
    <?php endif; ?>

    <?php if ($this->reportAction == 'print'): ?>
    <div class="trace-container">
        <div class="trace">
            <pre><?php echo $this->reportData[0] ?><br />
<strong>Trace:</strong>
<?php echo htmlspecialchars($this->reportData[1]) ?><br />
</pre>
        </div>
    </div>
    <?php endif; ?>
    <?php if ($this->reportId && $this->reportUrl): ?>
        <p>Error log record number: <a href="<?php echo htmlspecialchars($this->reportUrl) ?>"><?php echo $this->reportId ?></a></p>
    <?php endif; ?>
</div>
