<?php
/**
 * Wicked awesome responsive theme for Magento.
 *
 * @category    Ash
 * @package     Ash_Yeti
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/** @var $this Mage_Paypal_Block_Express_Review */
?>
<div id="shipping-method-container" class="fieldset">
<?php if ($this->getCanEditShippingMethod() || !$this->getCurrentShippingRate()):?>
        <?php if ($groups = $this->getShippingRateGroups()):?>
            <?php $currentRate = $this->getCurrentShippingRate(); ?>
            <select name="shipping_method" id="shipping_method" style="width:250px;" class="required-entry">
            <?php if (!$currentRate):?>
                <option value=""><?php echo $this->__('Please select a shipping method...') ?></option>
            <?php endif;?>
            <?php foreach ($groups as $code => $rates):?>
                <optgroup label="<?php echo $this->escapeHtml($this->getCarrierName($code)) ?>" style="font-style:normal;">
                <?php foreach ($rates as $rate):?>
                    <option value="<?php echo $this->renderShippingRateValue($rate)?>"<?php echo ($currentRate === $rate) ? ' selected="selected"' : '' ;?>>
                        <?php echo $this->renderShippingRateOption($rate)?>
                    </option>
                <?php endforeach;?>
                </optgroup>
            <?php endforeach;?>
            </select>
        <?php else: ?>
            <p><strong><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></strong></p>
        <?php endif;?>
<?php else: ?>
    <p><strong><?php echo $this->renderShippingRateOption($this->getCurrentShippingRate())?></strong></p>
<?php endif; ?>
</div>
<div style="display:none" id="shipping_method_update"><p><?php echo $this->__('Please update order data to get shipping methods and rates') ?></p></div>
