<?php
/**
 * Yeti
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 Yeti Theme. (https://github.com/augustash/yeti)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" id="top" class="no-js"> <!--<![endif]-->

<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page row">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main-container col3-layout large-12 columns">
            <div class="main row">
                <?php echo $this->getChildHtml('breadcrumbs') ?>

                <div class="medium-12 large-9 columns">

                    <div class="col-wrapper row">

                        <?php // This left_first block will display above the main content on smaller viewports ?>
                        <?php if ($_leftContent = $this->getChildHtml('left_first')): ?>
                            <div class="col-left sidebar col-left-first medium-4 columns"><?php echo $_leftContent;   ?></div>
                        <?php endif; ?>

                        <div class="col-main medium-8 columns">
                            <?php echo $this->getChildHtml('global_messages') ?>
                            <?php echo $this->getChildHtml('content') ?>
                        </div>

                        <div class="col-left sidebar medium-4 columns"><?php echo $this->getChildHtml('left') ?></div>
                    </div>

                </div>

                <div class="col-right sidebar large-3 columns"><?php echo $this->getChildHtml('right') ?></div>

            </div>
        </div>
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
