<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>

<!--[if gte IE 9]><!-->
<?php echo $this->getCssJsHtml() ?>
<!--<![endif]-->

<script type="text/javascript">
//<![CDATA[
jQuery(document).foundation({
	topbar : {
		custom_back_text: true,
		back_text: '<i class="fa fa-angle-left"></i> Back',
		mobile_show_parent_link: true
	}
});
//]]>
</script>
