<?php
/**
 * Yeti
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 Yeti Theme. (https://github.com/augustash/yeti)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="footer-container large-12 columns">
    <div class="footer">
        <?php echo $this->getChildHtml() ?>
        <address class="copyright"><?php echo $this->getCopyright() ?></address>
    </div>
</div>
