<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>

<footer class="site-footer row">
    <div class="site-footer-content large-12 columns">
        <div class="credits">&copy; <?php echo date("Y"); ?> Ash Foundation. All Rights Reserved. Website by <a href="http://www.augustash.com">August Ash</a>.</div>
    </div>
</footer>