<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<?php
/**
 * @see Mage_Page_Block_Html_Notices
 */
?>
<?php if ($this->displayNoscriptNotice()): ?>
    <noscript>
        <div class="global-site-notice noscript alert-box warning">
            <strong><?php echo $this->__('JavaScript seems to be disabled in your browser.'); ?></strong><br />
            <?php echo $this->__('You must have JavaScript enabled in your browser to utilize the functionality of this website.'); ?>
        </div>
    </noscript>
<?php endif; ?>
<?php if ($this->displayDemoNotice()): ?>
    <div class="global-site-notice demo-notice alert-box info">
        <?php echo $this->__('This is a demo store. Any orders placed through this store will not be honored or fulfilled.') ?>
    </div>
<?php endif; ?>
