<?php
/**
 * Wicked awesome responsive theme for Magento Enterprise.
 *
 * @category    Ash
 * @package     Ash_Yetiee
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /* @var $this Mage_Sales_Block_Recurring_Profiles */ ?>
<div class="page-title">
    <h1><?php echo $this->__('Recurring Profiles') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="recurring-profiles">

    <?php echo $this->getChildHtml('grid')?>

    <div class="buttons-set">
        <hr>
        <a class="back-link button link" href="<?php echo $this->escapeHtml($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a>
    </div>
</div>
