<?php
/**
 * Wicked awesome responsive theme for Magento Enterprise.
 *
 * @category    Ash
 * @package     Ash_Yetiee
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="box-account box-info">
    <div class="box-head">
        <h3><?php echo $this->__('Address Book') ?></h3>
        <a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a>
    </div>
    <div class="row">
        <div class="medium-6 columns">
            <div class="box-info">
                <div class="box-title">
                    <h5><?php echo $this->__('Default Billing Address') ?></h5>
                    <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit') ?></a>
                </div>
                <div class="box-content">
                    <address><?php echo $this->getPrimaryBillingAddressHtml() ?></address>
                </div>
            </div>
        </div>
        <div class="medium-6 columns">
            <div class="box">
                <div class="box-title">
                    <h5><?php echo $this->__('Default Shipping Address') ?></h5>
                    <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit') ?></a>
                </div>
                <div class="box-content">
                    <address><?php echo $this->getPrimaryShippingAddressHtml() ?></address>
                </div>
            </div>
        </div>
    </div>
</div>
