<?php
/**
 * Yeti
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 Yeti Theme. (https://github.com/augustash/yeti)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="box-account box-info">
    <div class="box-head">
        <h2><?php echo $this->__('Address Book') ?></h2>
        <a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a>
    </div>
    <div class="col2-set row">
        <div class="col-1 medium-6 columns">
            <div class="box">
                <div class="box-title">
                    <h3><?php echo $this->__('Default Billing Address') ?></h3>
                    <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
                </div>
                <div class="box-content">
                    <address><?php echo $this->getPrimaryBillingAddressHtml() ?></address>
                </div>
            </div>
        </div>
        <div class="col-2 medium-6 columns">
            <div class="box">
                <div class="box-title">
                    <h3><?php echo $this->__('Default Shipping Address') ?></h3>
                    <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
                </div>
                <div class="box-content">
                    <address><?php echo $this->getPrimaryShippingAddressHtml() ?></address>
                </div>
            </div>
        </div>
    </div>
</div>
