<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<div class="buttons-set">
	<hr>
    <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link button secondary"><i class="fa fa-angle-left"></i> <?php echo $this->__('Back') ?></a>
</div>
