<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php if($this->getItemCount()): ?>
<div class="crosssell">
    <h2><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>
    <div class="row">
    <?php foreach ($this->getItems() as $_item): ?>
        <div class="item columns large-4">
           <div class="product-details">
               <div class="row">
                <a class="product-image columns large-4 small-6" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(120); ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                <div class="columns large-8 small-6">
                    <h4 class="product-name">
                        <a href="<?php echo $_item->getProductUrl() ?>">
                            <?php echo $this->htmlEscape($_item->getName()) ?></a>
                    </h4>

                    <p><?php echo $this->htmlEscape($_item->getShortDescription()) ?></p>
                </div>
               </div>

               <div class="row collapse">
                   <div class="columns large-6 small-6">
                       <?php echo $this->getPriceHtml($_item, true) ?>
                   </div>
                    <div class="columns large-6 small-6">
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart small" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    </div>
               </div>

                <div class="row collapse">
                    <div class="columns large-12 add-to-links">

                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <div class="columns large-6 small-6"><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></div>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
                            <div class="columns large-6 small-6"><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></div>
                        <?php endif; ?>

                    </div>
                </div>

            </div>
        </div>

    <?php endforeach; ?>
    </div>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
</div>
<?php endif; ?>
