<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<div class="row">
    <div class="medium-8 medium-offset-2 columns">
        <div class="page-title">
            <h1><?php echo $this->__('Shopping Cart is Empty') ?></h1>
        </div>
        <div class="cart-empty">
            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
            <?php echo $this->getChildHtml('checkout_cart_empty_widget'); ?>
            <p><?php echo $this->__('You have no items in your shopping cart.') ?></p>
            <p><?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getContinueShoppingUrl()) ?></p>
            <?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
        </div>
    </div>
</div>
