<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<?php
/**
 * Shopping cart totals template
 *
 * @see Mage_Checkout_Block_Cart_Totals
 * @var $this Mage_Checkout_Block_Cart_Totals
 */
?>
<div class="cart-total">
    <h3><?php echo $this->__('Cart Total') ?></h3>
    <?php if ($this->canApplyMsrp()): ?>
        <div class="cart-msrp-totals"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></div>
    <?php else: ?>
        <table id="shopping-cart-totals-table">
            <col />
            <col width="1" />
            <tfoot>
                <?php echo $this->renderTotals('footer'); ?>
            </tfoot>
            <tbody>
                <?php echo $this->renderTotals(); ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>