<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="row">
    <div class="medium-8 medium-offset-2 columns">
        <div class="page-title">
            <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
        </div>
        <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
            <div class="fieldset">
                <h3 class="legend"><?php echo $this->__('Retrieve your password here') ?></h3>
                <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
                <ul class="form-list no-bullet">
                    <li>
                        <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="email" placeholder="<?php echo $this->__('johndoe@example.com') ?>" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                </ul>
            </div>
            <div class="buttons-set">
                <hr>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                <ul class="inline-list">
                    <li><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link button secondary"><i class="fa fa-angle-left"></i> <?php echo $this->__('Back') ?></a></li>
                    <li class="right"><button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><?php echo $this->__('Submit') ?></button></li>
                </ul>
            </div>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            var dataForm = new VarienForm('form-validate', true);
        //]]>
        </script>  
    </div>
</div>
