<?php
/**
 * Wicked awesome responsive theme for Magento Enterprise.
 *
 * @category    Ash
 * @package     Ash_Yetiee
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Newsletter Subscription') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h3 class="legend"><?php echo $this->__('Newsletter Subscription') ?></h3>
        <ul class="form-list no-bullet">
            <li class="control"><input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="subscription"><?php echo $this->__('General Subscription') ?></label></li>
            <?php /* Extensions placeholder */ ?>
            <?php echo $this->getChildHtml('customer.form.newsletter.extra')?>
        </ul>
    </div>
    <div class="buttons-set">
        <hr>
        <a class="back-link button link" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button right"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('customer.form.newsletter.extra2')?>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
