<?php
/**
 * Wicked awesome responsive theme for Magento.
 *
 * @category    Ash
 * @package     Ash_Yeti
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Mustishipping state
 *
 * @see Mage_Checkout_Block_Multishipping_State
 */
?>
<ul class="checkout-progress no-bullet" id="checkout-progress-state">
<?php foreach ($this->getSteps() as $_step): ?>
    <li title="<?php echo $_step->getLabel() ?>"<?php if($_step->getIsActive()): ?> class="active"<?php endif; ?>><span><?php echo $_step->getLabel() ?></span></li>
<?php endforeach; ?>
</ul>
<script type="text/javascript">decorateGeneric($$('#checkout-progress-state li'), ['first','last']);</script>
