<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>
<?php $_links = $this->getLinks(); ?>
<?php if(count($_links)>0): ?>
<div id="mtab-2" class="mtabs clearfix">
	<ul <?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?> class="top-links no-bullet">
		<li class="my-cart show-for-large-up">
			<a href="#" data-dropdown="mtab-1" class="my-cart" title="My Cart">
				<span class="cart-text">My Cart </span>
				<span class="amount">
				<?php $count = $this->helper('checkout/cart')->getSummaryCount();
					if($count==0) {
						echo $this->__('(0)');
					}
					if($count>0) {
						echo $this->__('(%s)', $count);
					}
				?>
				</span> <i class="fa fa-caret-down"></i>
			</a>
		</li>
	    <?php foreach($_links as $_link): ?>
	        <?php if ($_link instanceof Mage_Core_Block_Abstract):?>
	            <?php echo $_link->toHtml() ?>
	        <?php else: ?>
	            <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?><?php if($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
	        <?php endif;?>
	    <?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>
