<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<div class="box-collateral box-tags">
    <h2><?php echo $this->__('Product Tags') ?></h2>
    <?php echo $this->getChildHtml('list_before')?>
    <?php if( $this->getCount() ): ?>
    <h4 class="subheader"><?php echo $this->__('Other people marked this product with these tags:') ?></h4>
    <ul id="<?php echo $this->getUniqueHtmlId('product-tags_'); ?>" class="product-tags inline-list">
        <?php echo $this->renderTags('<li><a href="%1$s">%2$s (%3$s)</a></li>') ?>
    </ul>
    <script type="text/javascript">
        decorateGeneric($("<?php echo $this->getUniqueHtmlId('product-tags_'); ?>").select('li'), ['first', 'last']);
    </script>
    <?php endif; ?>
    <form id="addTagForm" action="<?php echo $this->getFormAction(); ?>" method="get">
        <div class="form-add row collapse">
            <label for="productTagName"><?php echo $this->__('Add Your Tags:') ?></label>
            <div class="input-box small-9 medium-10 columns">
                <input type="text" class="input-text required-entry" name="productTagName" id="productTagName" />
            </div>
            <div class="small-3 medium-2 columns">
                <button type="button" title="<?php echo $this->__('Add Tags') ?>" class="button postfix" onclick="submitTagForm()"><i class="fa fa-tags"></i> <?php echo $this->__('Add Tags') ?></button>
            </div>
        </div>
    </form>
    <p class="note"><?php echo $this->__("Use spaces to separate tags. Use single quotes (') for phrases.") ?></p>
    <script type="text/javascript">
    //<![CDATA[
        var addTagFormJs = new VarienForm('addTagForm');
        function submitTagForm(){
            if(addTagFormJs.validator.validate()) {
                addTagFormJs.form.submit();
            }
        }
    //]]>
    </script>
</div>
