<?php
/**
 * Wicked awesome responsive theme for Magento Enterprise.
 *
 * @category    Ash
 * @package     Ash_Yetiee
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<h2><?php echo $this->__('Product Tags') ?></h2>
<?php echo $this->getChildHtml('list_before')?>
<?php if( $this->getCount() ): ?>
<h3><?php echo $this->__('Other people marked this product with these tags:') ?></h3>
<ul id="<?php echo $this->getUniqueHtmlId('product-tags_'); ?>" class="product-tags">
    <?php echo $this->renderTags('<li><a href="%1$s">%2$s</a> (%3$s)</li>') ?>
</ul>
<script type="text/javascript">
    decorateGeneric($("<?php echo $this->getUniqueHtmlId('product-tags_'); ?>").select('li'), ['first', 'last']);
</script>
<?php endif; ?>
<form id="addTagForm" action="<?php echo $this->getFormAction(); ?>" method="get">
    <div class="form-add row collapse">
        <label for="productTagName"><?php echo $this->__('Add Your Tags:') ?></label>
        <div class="input-box small-9 columns">
            <input type="text" class="input-text required-entry" name="productTagName" id="productTagName" />
        </div>
        <div class="small-3 columns">
            <button type="button" title="<?php echo $this->__('Add Tags') ?>" class="button postfix" onclick="submitTagForm()"><?php echo $this->__('Add Tags') ?></button>
        </div>
    </div>
</form>
<p class="note"><?php echo $this->__("Use spaces to separate tags. Use single quotes (') for phrases.") ?></p>
<script type="text/javascript">
//<![CDATA[
    var addTagFormJs = new VarienForm('addTagForm');
    function submitTagForm(){
        if(addTagFormJs.validator.validate()) {
            addTagFormJs.form.submit();
        }
    }
//]]>
</script>
