<?php
/**
 * Wicked awesome responsive theme for Magento Enterprise.
 *
 * @category    Ash
 * @package     Ash_Yetiee
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="block block-tags">
    <div class="block-title">
        <strong><span><?php echo $this->__('Popular Tags'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="tags-list no-bullet">
            <?php foreach ($this->getTags() as $_tag): ?>
                <li><a href="<?php echo $_tag->getTaggedProductsUrl() ?>" style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;"><?php echo $this->escapeHtml($_tag->getName()) ?></a></li>
            <?php endforeach; ?>
        </ul>
        <div class="actions">
            <a class="button tiny secondary no-margin" href="<?php echo $this->getUrl('tag/list') ?>"><?php echo $this->__('View All Tags') ?></a>
        </div>
    </div>
</div>
