<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */

/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart */
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
$options = $this->getChild('customer.wishlist.item.options')
    ->setItem($item)
    ->getConfiguredOptions();
?>
<div class="cart-cell">
<?php echo $this->getPriceHtml($product, empty($options));?>
<div class="add-to-cart-alt">
<?php if ($item->canHaveQty() && $item->getProduct()->isVisibleInSiteVisibility()): ?>
    <input type="text" class="input-text qty validate-not-negative-number" name="qty[<?php echo $item->getId() ?>]" value="<?php echo $this->getAddToCartQty($item) * 1 ?>" />
<?php endif; ?>
<?php if ($product->isSaleable()): ?>
    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" onclick="addWItemToCart(<?php echo $item->getId()?>);" class="small button expand btn-cart"><?php echo $this->__('Add to Cart') ?></button>
<?php else: ?>
    <?php if ($product->getIsSalable()): ?>
        <p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
    <?php else: ?>
        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
    <?php endif; ?>
<?php endif; ?>
</div>
<?php foreach($this->getSortedChildren() as $childName):?>
    <?php echo $this->getChildHtml($childName, false);?>
<?php endforeach;?>
<?php if ($product->isVisibleInSiteVisibility()): ?>
    <p><a class="link-edit" href="<?php echo $this->getItemConfigureUrl($item) ?>"><i class="fa fa-pencil"></i> <?php echo $this->__('Edit') ?></a></p>
<?php endif ?>
</div>
