<?php
/**
 * Wicked awesome responsive theme for Magento Enterprise.
 *
 * @category    Ash
 * @package     Ash_Yetiee
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<a href="<?php echo $this->getItemRemoveUrl($this->getItem()); ?>" onclick="return confirmRemoveWishlistItem();" title="<?php echo $this->__('Remove Item') ?>"
    class="btn-remove btn-remove2"><i class="fa fa-trash-o"></i></a>
