<?php
/**
 * Wicked awesome responsive theme for Magento Enterprise.
 *
 * @category    Ash
 * @package     Ash_Yetiee
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var Mage_Page_Block_Html_Topmenu_Renderer $this */
/** @var Varien_Data_Tree_Node $menuTree */
/** @var string $childrenWrapClass */

$html = '';

$children = $menuTree->getChildren();
$parentLevel = $menuTree->getLevel();
$childLevel = is_null($parentLevel) ? 0 : $parentLevel + 1;

$counter = 1;
$childrenCount = $children->count();

$parentPositionClass = $menuTree->getPositionClass();
$itemPositionClassPrefix = $parentPositionClass ? $parentPositionClass . '-' : 'nav-';

foreach ($children as $child) {

    $child->setLevel($childLevel);
    $child->setIsFirst($counter == 1);
    $child->setIsLast($counter == $childrenCount);
    $child->setPositionClass($itemPositionClassPrefix . $counter);

    $outermostClassCode = '';
    $outermostClass = $menuTree->getOutermostClass();

    if ($childLevel == 0 && $outermostClass) {
        $outermostClassCode = ' class="' . $outermostClass . '" ';
        $child->setClass($outermostClass);
    }

    $html .= '<li ' . $this->_getRenderedMenuItemAttributes($child) . '>';
    $html .= '<a href="' . $child->getUrl() . '" ' . $outermostClassCode . '><span>'
        . $this->escapeHtml($child->getName()) . '</span></a>';

    if ($child->hasChildren()) {
        if (!empty($childrenWrapClass)) {
            $html .= '<div class="' . $childrenWrapClass . '">';
        }
        $html .= '<ul class="level' . $childLevel . '">';
        $html .= $this->_getHtml($child, $childrenWrapClass);
        $html .= '</ul>';

        if (!empty($childrenWrapClass)) {
            $html .= '</div>';
        }
    }
    $html .= '</li>';

    $counter++;
}

return $html;
