<?php
/**
 * Wicked awesome responsive theme for Magento.
 *
 * @category    Ash
 * @package     Ash_Yeti
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="dashboard">
    <div class="page-title">
        <h1><?php echo $this->__('My Dashboard') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php echo $this->getChildHtml('hello') ?>
    <?php echo $this->getChildHtml('top') ?>
    <div class="box-account box-info">
        <div class="box-head">
            <h3><?php echo $this->__('Account Information') ?></h3>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('customer.account.dashboard.extra') ?>
        <?php echo $this->getChildHtml('info') ?>
    </div>
    <?php echo $this->getChildHtml('address') ?>
    <?php echo $this->getChildHtml('info1') ?>
    <?php echo $this->getChildHtml('info2') ?>
</div>
