<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title">
    <h1><?php echo $this->__('My Tags') ?></h1>
</div>
<?php if($this->getTags()): ?>
    <p><?php echo $this->__('Click on a tag to view your corresponding products.') ?></p>
    <ul class="tags-list">
        <?php foreach ($this->getTags() as $_tag): ?>
            <li><a href="<?php echo $this->getUrl('tag/customer/view', array('tagId' => $_tag->getTagId())) ?>" style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;"><?php echo $this->escapeHtml($_tag->getName()) ?></a></li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p><?php echo $this->__('You have not tagged any products yet.') ?></p>
<?php endif; ?>
<div class="buttons-set">
    <hr>
    <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link button secondary"><i class="fa fa-angle-left"></i> <?php echo $this->__('Back') ?></a>
</div>
