<?php
/**
 * Wicked awesome responsive theme for Magento.
 *
 * @category    Ash
 * @package     Ash_Yeti
 * @copyright   Copyright (c) 2015 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if(count($this->getItemCollection()->getItems())): ?>
<h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
<div class="box-collateral box-up-sell">
    <div class="products-grid" id="upsell-product-table">
    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
        <ul class="small-block-grid-1 medium-block-grid-3 large-block-grid-4">
        <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
            <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
                <?php if($_link=$this->getIterableItem()): ?>
                <li class="item">
                    <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>" class="th product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(150) ?>" alt="<?php echo $this->escapeHtml($_link->getName()) ?>" /></a>
                    <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>"><?php echo $this->escapeHtml($_link->getName()) ?></a></h3>
                    <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
                    <?php echo $this->getReviewsSummaryHtml($_link) ?>
                </li>
                <?php endif; ?>
            <?php endfor; ?>
        <?php endfor; ?>
        </ul>
    </div>
    <script type="text/javascript">decorateTable('upsell-product-table')</script>
</div>
<?php endif ?>
