<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<?php if( $this->getCollection() && $this->count()): ?>
<div class="box-account box-reviews">
    <div class="box-head clearfix">
        <h2 class="left"><?php echo $this->__('My Recent Reviews') ?></h2>
        <a class="right" href="<?php echo $this->getAllReviewsUrl() ?>"><?php echo $this->__('View All Reviews') ?></a>
    </div>
    <ol id="my_recent_reviews">
    <?php $iterator = 0 ?>
    <?php foreach ($this->getCollection() as $_review): ?>
        <li class="item">
            <span class="number"><?php echo ++$iterator ?></span>
            <div class="details">
                <h3 class="product-name"><a href="<?php echo $this->getReviewUrl($_review->getReviewId()) ?>"><?php echo $this->escapeHtml($_review->getName()) ?></a></h3>
                <?php if($_review->getSum()): ?>
                    <div class="ratings">
                        <strong><?php echo $this->__('Rating:') ?></strong>
                        <div class="rating-box">
                            <div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('my_recent_reviews');</script>
</div>
<?php endif; ?>
