<?php
/**
 * Magento theme built on Zurb Foundation
 *
 * @category    design
 * @package     yeti_default
 * @copyright   Copyright (c) 2014 August Ash (http://www.augustash.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      August Ash <code@augustash.com>
 */
?>
<?php
/**
 * Customer "Remember Me" template
 *
 */
/** @var $this Mage_Persistent_Block_Form_Remember */
?>
<li>
    <div id="remember-me-box" class="input-box remember-me">
        <?php $rememberMeId = 'remember_me' . Mage::helper('core')->getRandomString(10); ?>
        <input type="checkbox" name="persistent_remember_me" class="input-checkbox" id="<?php echo $rememberMeId; ?>"<?php if ($this->isRememberMeChecked()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Remember Me') ?>" />
        <label for="<?php echo $rememberMeId; ?>"><?php echo $this->__('Remember Me') ?></label>
        <a href="#"><?php echo $this->__('What\'s this?') ?></a>
    </div>
</li>
